# version: "3"

# services:
#   mongodb:
#     image: mongo:latest
#     container_name: my-mongodb
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: mongoadmin
#       MONGO_INITDB_ROOT_PASSWORD: secret
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:

# Use root/example as user/password credentials
version: "2"

services:
  mongo:
    image: "mongo:3.6"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
